---
title: How to generate a random password in Groovy?
date: 2022-02-14 12:44:06
updated: 2022-02-14 12:44:06
categories:
- Groovy Cookbook
tags:
- groovy
- random
- tips
- string
card: /images/cards/7.png
affiliates: true
highlightjs: true
related:
- groovy-regular-expressions-the-definitive-guide
- tail-recursive-methods-in-groovy
- groovy-string-methods-that-will-make-your-life-groovier
- graalvm-and-groovy-how-to-start
icon: /images/icons/28.png
---

Sometimes you need to generate a random password (or just random string of any kind.)
Today I will show you how to do it with a single line of code in Groovy 3 (or newer.)

++++
<!-- more -->
++++

The complete code that generates a random password in Groovy looks like this:

[source,groovy]
----
('z'..'0').shuffled().take(10).join()
----

Let's deconstruct this example and understand what each part of this code mean.

The first part of that code `('z'..'0')` creates a range of characters.
If we convert it to a list, we would get a list of the following characters:

[source,groovy]
----
[z, y, x, w, v, u, t, s, r, q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a, `, _, ^, ], \, [, Z, Y, X, W, V, U, T, S, R, Q, P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A, @, ?, >, =, <, ;, :, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
----

As you can see, the list contains:

* lower-case letters,
* upper-case letters,
* digits,
* and several special characters.

In the next part, we call `shuffled()` method on the generated range to convert it to a list and shuffle the order of its elements.

NOTE: Keep in mind that the `shuffled()` method was introduced in Groovy 3.0.

Once the list of characters is shuffled, we take the first ten elements from it using the `take(10)` method call.

And last but not least, we call `join()` method to create a string from a list of characters.

WARNING: The example shown in this blog post does not guarantee that the generated password contains e.g. at least one special character and/or one digit.

[source,groovy]
----
Groovy Shell (4.0.0, JVM: 11.0.10)
Type ':help' or ':h' for help.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
groovy:000> ('z'..'0').shuffled().take(10).join()
===> 7@R162?nIv
groovy:000> ('z'..'0').shuffled().take(10).join()
===> O]TR84[syY
groovy:000> ('z'..'0').shuffled().take(10).join()
===> vx^[rM4g<d
groovy:000> ('z'..'0').shuffled().take(10).join()
===> 2Cv7AYgcSd
groovy:000> ('z'..'0').shuffled().take(10).join()
===> 7i`Zf[IRDy
groovy:000> ('z'..'0').shuffled().take(10).join()
===> ClKIjVTxcB
groovy:000> ('z'..'0').shuffled().take(10).join()
===> bU^[G5oE?T
groovy:000> ('z'..'0').shuffled().take(10).join()
===> tf\MmJ=SHp
----