---
title: 1% better, every day
date: 2020-05-01 21:42:11
layout: clean
---
:check: icon:check-square-o[role="color-green"]

== Monday, May 4th, 2020

[.nobullets]
* {check} I learned how to set up Bitbucket Server 7.1 web hooks to Jenkins server (solved problem after Bitbucket upgrade.)
* {check} I explored early Groovy syntax (pre 1.0) and learned that for-each loop syntax was introduced in Java 1.5.

== Sunday, May 3rd, 2020

[.nobullets]
* {check} I learned about cool-retro-term and crafted an idea for a future video series.

== Saturday, May 2nd, 2020

[.nobullets]
* {check} I learned multimethods in Clojure.
* {check} I learned about Ring - Clojure library for building lightweight HTTP servers.


== Friday, May 1st, 2020

[.nobullets]
:hexo-tag-share-post: https://github.com/wololock/hexo-tag-share-post
:avajs: https://github.com/avajs/ava
:hexo-test-utils: https://github.com/ertrzyiks/hexo-test-utils
* {check} Created my first nodejs open-source project - {hexo-tag-share-post}[hexo-tag-share-post] plugin.
* {check} Learned how to write unit tests using {avajs}[ava testing framework] and {hexo-test-utils}[hexo-test-utils].
* {check} Published and unpublished my very first npm package.