---
title: Support me
date: 2020-03-27 08:19:25
layout: clean
---
:buy-me-a-coffee: https://e.printstacktrace.blog/buy-me-a-coffee?utm_source=support
:codementor: https://www.codementor.io/@szymonstpniak
:youtube: https://e.printstacktrace.blog/youtube?utm_source=support
:twitter: https://twitter.com/wololock
:books: https://e.printstacktrace.blog/tags/affiliate/
:email-me: mailto:szymon.stepniak@gmail.com
:kitco: https://kit.co/wololock

I hate ads and popups showing up a few seconds after visiting a website.
That is why I decided to keep my blog free from those annoying elements.
I care about excellent user experience, and my goal is to offer you one that can be compared to reading an ebook.
No distracting banners, no ads, no stupid popups.
Just clean and well-formatted content.

Does it mean that I don't want to monetize my blog by any form?
Not necessarily.
I just believe that there are better forms to do that.
In the last 6 months (from October 1st, 2019 to March 27th, 2020), more than *110,000 unique users* visited my blog.
I don't expect support from every reader, this is unrealistic.
But I believe there is a chance that 1% of my readers (or my YouTube subscribers) could support my work and effort in one way or another.
Would you like to be *my top 1% reader*?

== How to support my work?

* If you buy books (or other stuff) online, you can check {kitco}["my Kit.co profile", role="ga-track"] where I created a few kits/collections containing books and equipment I use and recommend. If you decide to buy anything through my affiliate link, I will receive *a small commission* from your purchase.
+
NOTE: *Buying through the affiliate link does not affect the total purchase price*. Any commission I earn from your purchase comes at no additional cost to you.
+
Here are a few kits I created that you may find interesting. However, *please do not spend any money on these products unless you feel they are useful and valuable to you.*
+
** https://kit.co/wololock/groovy-programmer-learning-kit["Groovy Programmer Learning Kit", role="ga-track"]
** https://kit.co/wololock/jenkins-pipeline-learning-kit["Jenkins Pipeline Learning Kit", role="ga-track"]
** https://kit.co/wololock/java-programmer-learning-kit["Java Programmer Learning Kit", role="ga-track"]
** https://kit.co/wololock/my-youtube-studio-equipment["My YouTube Studio Equipment Kit", role="ga-track"]
* Maybe you are looking for *online mentoring*? You can find me on {codementor}[Codementor.io] and schedule a session. You read my blog, so you know what are my strong points and competences. I can help you solve an urgent problem, or share my experience with you in longer mentoring relationship to help you become a better problem solver.
* I love slow brew coffee. Do you? You can {buy-me-a-coffee}[buy me one, role="ga-track"] through PayPal donation, I will be grateful for that.
* Did you know that I also record YouTube videos? {youtube}[Subscribing to my channel, role="ga-track"], *commenting* videos and hitting that *like button* is also a great way to show support.
* Do you use Twitter? {twitter}[I do]. You can help me by *sharing my blog posts* with people that follow you.
* And last but not least, you can {email-me}[email me] and just say "Thanks" if any of my blog posts were useful to you.

== What do I need the extra money for?

The maintenance cost of my blog is quite low.
I use GitHub Pages to host the static website, I use Cloudflare free plan to manage DNS, SSL, and some necessary network protection.
However, there are some additional costs and investments I would like to cover with your help, that includes:

* Annual domain renewal. (~$50/yr)
* Annual Disqus Plus (free plan adds some random ads around comment's section.) (~$108/yr)
* Annual Grammarly.com subscription. (~$140/yr)
* Investing in video/audio gear to produce better quality content.
* Investing in products and services that help me to deliver high-quality blog posts.

== Thank you!

Thank you for reading up to this point.
I hope you are a returning happy reader of my blog.
If you can afford to support my work, I will be thankful.
But don't feel forced to it.
I will continue doing my work on the blog and on my YouTube channel.
I enjoy it, and I see that my effort is not pointless - I keep getting thankful messages from you and that makes me really proud and happy.
*Keep learning, keep coding, and have fun!*

[%hardbreaks]
Yours sincerely,
Szymon