---
title: Privacy policy
date: 2019-03-24 12:14:58
layout: clean
---

Last update: *March 26th, 2019*

*e.printstacktrace.blog* (also hereinafter referred to as the "Blog") does not share any personal information with
third-parties nor does it store information collected about your visit to this blog for use other than to analyze
content performance through the use of cookies, which you can turn off at any time by modifying your
web browser's settings.

* https://support.google.com/chrome/answer/95647?hl=en&p=cpn_cookies[for Google Chrome users]
* https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences[for Mozilla Firefox users]
* https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/[for Apple Safari users]
* https://windows.microsoft.com/en-us/windows-vista/block-or-allow-cookies[for Microsoft Internet Explorer users]


== Cookies

A web cookie is a small piece of data sent from a website and stored on the user's computer by the user's web
browser while the user is browsing.footnote:[https://en.wikipedia.org/wiki/HTTP_cookie] *e.printstacktrace.blog*
uses a minimum amount of cookies from third-party services. The full list of those services can be found below.

=== 1. Google Analytics

Like almost every other website, this "Blog" uses *Google Analyticsfootnote:[https://analytics.google.com/analytics/web/]*, a service provided by Google, Inc. for
a web traffic tracking. Learn more about https://www.google.com/policies/privacy/[Google Analytics Privacy Politics].

NOTE: Google allows you to *opt-out from sending usage data* to Google Analytics by https://tools.google.com/dlpage/gaoptout?hl=en[installing the following plugin]
to your favorite web browser.

=== 2. Cloudflare

This "Blog" uses *Cloudflarefootnote:[https://www.cloudflare.com/]* to secure and speed up serving the "Blog" content.
Cloudflare acts as a&nbsp;proxy server between your web browser and Github Pages server. For this purpose, Cloudflare stores
some information in the `_cfduid` cookie.
Learn more about https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-Cloudflare-cfduid-cookie-do-[what does this cookie do]
and https://support.cloudflare.com/hc/en-us/articles/360024915491[its privacy].

=== 3. Disqus

This "Blog" uses *Disqusfootnote:[https://disqus.com/]*, an online public comment sharing platform. Adding comments on
the "Blog" is tantamount to acceptance of Disqus' https://help.disqus.com/terms-and-policies/terms-of-service[Terms of use]
and https://help.disqus.com/terms-and-policies/disqus-privacy-policy[Privacy policy].

=== 4. YouTube videos

Some of the "Blog" posts are also delivered with embedded *YouTube* (owned by Google, Inc.) videos. YouTube also collect
some information in web cookies to capture video display statistics, improve user experience and protect from abusive practices.
This information is directly associated with your Google account. To prevent the data from being associated with your account,
please consider logging off before playing the video. You can learn more about https://policies.google.com/privacy[Google's Privacy Policy].

=== 5. Amazon Associates

Some of the "Blog" posts contain *Amazon Associatesfootnote:[https://affiliate-program.amazon.com/]* affiliation links generated with Amazon OneLinkfootnote:[https://affiliate-program.amazon.com/help/node/topic/202164400].
Affiliation links are used only to earn a small commission from books recommendations. Blog posts with affiliation links
(and only those) use _oneTag_ JavaScript code provided by the Amazon Associates program. When this script gets loaded, it stores
two cookies in your web browser - `ad-id` and `ad-private`. These cookies exist only on pages with affiliation links (book reviews blog posts).


== Do you collect any server logs?

No. This "Blog" is hosted on *Github Pagesfootnote:[https://pages.github.com/]* thus it does not have access to any server logs.


== Encryption (HTTPS)

This "Blog" uses an encrypted transfer protocol (HTTPS over TLS) with the *ECC CA-2* certificate provides by CloudFlare, Inc.
The encryption protects the communication to *e.printstacktrace.blog* from access by unauthorized third parties.

== Do you collect any ads-related data?

No, *e.printstacktrace.blog* does not collect any ads-related data. There are no ads on this "Blog". And&nbsp;I&nbsp;don't plan to add any.

== Who can I contact if I have any questions?

If you have any questions, please contact the owner of this "Blog":

Szymon Stępniak
+++<br><i class="fa fa-envelope"></i>+++ szymon.stepniak@gmail.com


This privacy policy is subject to change without notice.